"""Agregue columna activo y sexo

Revision ID: 87ac2f6be5d4
Revises: 88a5dfe9db89
Create Date: 2024-01-26 20:49:17.711721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87ac2f6be5d4'
down_revision = '88a5dfe9db89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sexo', sa.String(length=50), server_default='NINGUNO', nullable=True))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), server_default='1', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('activo')
        batch_op.drop_column('sexo')

    # ### end Alembic commands ###
